// <auto-generated />
using Bootcamp.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bootcamp.WebApi.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("api")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bootcamp.WebApi.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FirstName", "LastName", "Email")
                        .HasDatabaseName("ix_users_first_name_last_name_email")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FirstName", "LastName", "Email"), "GIN");

                    b.ToTable("users", "api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rami.yousef@example.com",
                            FirstName = "Rami",
                            LastName = "Yousef",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 2,
                            Email = "lina.hassan@example.com",
                            FirstName = "Lina",
                            LastName = "Hassan",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 3,
                            Email = "sami.odeh@example.com",
                            FirstName = "Sami",
                            LastName = "Odeh",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 4,
                            Email = "nour.khalil@example.com",
                            FirstName = "Nour",
                            LastName = "Khalil",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 5,
                            Email = "alaa.ahmad@example.com",
                            FirstName = "Alaa",
                            LastName = "Ahmad",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 6,
                            Email = "faris.naser@example.com",
                            FirstName = "Faris",
                            LastName = "Naser",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 7,
                            Email = "dana.salem@example.com",
                            FirstName = "Dana",
                            LastName = "Salem",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 8,
                            Email = "khaled.mansour@example.com",
                            FirstName = "Khaled",
                            LastName = "Mansour",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 9,
                            Email = "tariq.zayed@example.com",
                            FirstName = "Tariq",
                            LastName = "Zayed",
                            RowVersion = 1u
                        },
                        new
                        {
                            Id = 10,
                            Email = "reem.haddad@example.com",
                            FirstName = "Reem",
                            LastName = "Haddad",
                            RowVersion = 1u
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
